Feature/course enroll
Kelompok-8-alterra/LMS-Frontend pull request #5
Opened 2021-12-23 09:18 UTC by daffaalex22

UI Kelar, Responsive, Mantap
![image](https://user-images.githubusercontent.com/67172568/147218021-f3ac8881-a8f1-4bac-b5ec-d82f96fe3761.png)
![image](https://user-images.githubusercontent.com/67172568/147218050-8e2ffea7-09ca-4504-a879-7512addd0edb.png)
![image](https://user-images.githubusercontent.com/67172568/147218073-5f5fb42d-4da2-4219-aef1-289194dbcd17.png)
![Uploading image.png…]()

2021-12-23 09:39 UTC, krisnadwipayana07 requested changes

2021-12-23 09:39 UTC, krisnadwipayana07 commented on src/components/FooterDashboard.js
>  import logoInEdu from '../assets/images/logoInEdu.svg';
kalo ini taruh di public gimana daff? nanti biar gampang ngeimportnya, biar ga nanti ubah file, ngulang settingnya wkwk

2021-12-23 09:39 UTC, krisnadwipayana07 commented on src/components/ReviewItem.js
> +                        src={Ava}
nanti kalo di publik langsung pakek slash kayak ngambil foto dari internet pakek link gitu

2021-12-28 04:19 UTC, krisnadwipayana07 approved these changes

2021-12-28 10:12 UTC, ilhamtri333 approved these changes

2021-12-28 10:12 UTC, merged